server:
  port: 8081
# DataSource Config
spring:
  application:
    name: halo-admin
  cloud:
    nacos:
      server-addr: nacos:8848
      username: nacos
      password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/halo_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mogu2018
  # Redis 数据库配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: mogu2018
  # rabbitmq
  rabbitmq:
    host: halo # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: mogu2018 # 密码
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml