server:
  port: 8888 # 网关端口
spring:
  application:
    name: halo-gateway
  cloud:
    nacos:
      server-addr: nacos:8848
      username: nacos
      password: nacos
    gateway:
      routes: # 网关路由配置
        - id: halo-web-gateway # 路由id，自定义，只要唯一即可
          uri: lb://halo-web # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/blog/** # 这个是按照路径匹配，只要以/blog/开头就符合要求