spring:
  # Redis 数据库配置
  redis:
    database: 0
    host: redis
    port: 6379
    password: mogu2018
  # rabbitmq
  rabbitmq:
    host: halo # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: mogu2018 # 密码
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议 默认就是smtp
    protocol: smtp
    # 编码格式 默认就是utf-8
    default-encoding: utf-8
    # 邮箱
    username: 1379978893@qq.com
    # 16位授权码 不是邮箱密码
    password:
    # smtp的指定端口 使用465要将protocol改为smtps
    port: 587
    # 设置开启ssl
    properties:
      mail:
        stmp:
          ssl:
            enable: true
halo:
  mail:
    username: Halo